# Generated by Django 3.1.4 on 2020-12-19 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('secondary_objects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_num', models.CharField(max_length=12, verbose_name='Phone number')),
                ('address', models.ManyToManyField(related_name='profile', to='secondary_objects.Address', verbose_name='Address')),
                ('phone_num_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secondary_objects.country', verbose_name='phone code num.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
