# Generated by Django 3.1.4 on 2020-12-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(default='profile_default.jpg', upload_to='profile_pics'),
        ),
    ]
