# Generated by Django 3.1.4 on 2021-01-07 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20210107_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available_for_drawing',
        ),
        migrations.AddField(
            model_name='product',
            name='is_draw',
            field=models.BooleanField(default=False, verbose_name='Is draw'),
        ),
    ]
