# Generated by Django 3.1.4 on 2021-01-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210114_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tickets_amount',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
