# Generated by Django 3.1.4 on 2021-01-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20210114_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='redemption_percent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
