# Generated by Django 3.1.4 on 2021-01-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
            preserve_default=False,
        ),
    ]
