# Generated by Django 3.1.4 on 2021-01-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_product_ticket_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
