# Generated by Django 3.1.4 on 2021-01-06 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondary_objects', '0003_auto_20201223_0338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
    ]
